CROSS_COMPILE =
PREFIX = $(CROSS_COMPILE)
CC = $(PREFIX)g++

CCFLAGS = -g3 -Wall -o0
LD = $(CC)
LDFLAGS = -lpthread

RM = rm -f

SOURCES_CPP = msg_recv.cpp Thread.cpp test_msgrcv.cpp
OBJECTS = $(SOURCES_CPP:%.cpp=%.o)

all: test_msgrcv
.PHONY : all

%.o: %.cpp
	$(CC) $(CCFLAGS) -c $< -o $@

test_msgrcv : $(OBJECTS)
	# $(LD) $(LDFLAGS) -o test_msgrcv $(OBJECTS)
	$(LD) -o test_msgrcv $(OBJECTS) $(LDFLAGS)

.PHONY : clean cleanall
clean:
	$(RM) *.o test_msgrcv

cleanall:
	$(RM) *.o test_msgrcv

