CROSS_COMPILE =
PREFIX = $(CROSS_COMPILE)
CC = $(PREFIX)g++

CCFLAGS = -g3 -Wall -o0
LD = $(CC)
LDFLAGS = -lpthread

RM = rm -f

SOURCES_CPP = test_msgsnd_cmd.cpp msgsnd_cmd.cpp
OBJECTS = $(SOURCES_CPP:%.cpp=%.o)

all: test_msgsnd_cmd
.PHONY : all

%.o: %.cpp
	$(CC) $(CCFLAGS) -c $< -o $@

test_msgsnd_cmd : $(OBJECTS)
	# $(LD) $(LDFLAGS) -o test_msgsnd_cmd $(OBJECTS)
	$(LD) -o test_msgsnd_cmd $(OBJECTS) $(LDFLAGS)

.PHONY : clean cleanall
clean:
	$(RM) *.o test_msgsnd_cmd

