CROSS_COMPILE =
PREFIX = $(CROSS_COMPILE)
CC = $(PREFIX)g++

CCFLAGS = -g3 -Wall -o0
LD = $(CC)
LDFLAGS = -lpthread

RM = rm -f

SOURCES_CPP = test_msgsnd.cpp msg_send.cpp
OBJECTS = $(SOURCES_CPP:%.cpp=%.o)

all: test_msgsnd
.PHONY : all

%.o: %.cpp
	$(CC) $(CCFLAGS) -c $< -o $@

test_msgsnd : $(OBJECTS)
	# $(LD) $(LDFLAGS) -o test_msgsnd $(OBJECTS)
	$(LD) -o test_msgsnd $(OBJECTS) $(LDFLAGS)

.PHONY : clean cleanall
clean:
	$(RM) *.o test_msgsnd

cleanall:
	$(RM) *.o test_msgsnd

