### Makefile --- 

## Author: weikent@ubuntu
## Version: $Id: Makefile,v 0.0 2014/07/16 02:11:21 weikent Exp $
## Keywords: 
## X-URL: 


.PHONY : all

all :
	$(MAKE) -f Makefile.selectServer
	$(MAKE) -f Makefile.selectClient
clean:
	$(MAKE) clean -f Makefile.selectServer
	$(MAKE) clean -f Makefile.selectClient



### Makefile ends here