### Makefile.test --- 

## Author: weishijian@weikents-Air.lan
## Version: $Id: Makefile.test,v 0.0 2017/03/15 05:04:55 weishijian Exp $
## Keywords: 
## X-URL: 





#CC=gcc
CC=mipsel-openwrt-linux-gcc
#CC=mipsel-linux-gcc
CXX = g++

VPATH = 
INCLUDE = 
WALL = -Wall
C99 = #-std=c99
THREAD = #-lpthread
OPTIMIZE = -O2
RM = rm -f


SOURCECPP =

SOURCEC =test.c msgQ.c

OBJECTSCPP = $(SOURCECPP:%.cpp=%.o)

OBJECTSC = $(SOURCEC:%.c=%.o)

OBJS = $(OBJECTSC) $(OBJECTSCPP)


TARGET = test

.PHONY = all
.PHONY = clean
all = clean $(TARGET)

%.o : %.c
	$(CC) -c $(WALL)  $< -o $@ $(INCLUDE) $(C99)

%.o : %.cpp
	$(CXX) -c $(WALL) $< -o $@ $(INCLUDE)

$(TARGET): $(OBJECTSC) $(OBJECTSCPP)
	$(CC) -o $(TARGET) $(INCLUDE)  $(OBJECTSC) $(OBJECTSCPP) $(THREAD) $(OPTIMIZE) $(C99)


clean:
	$(RM) $(OBJS) $(TARGET)

install:
#	cp *.h *.cpp *.c -r ../wpa




### Makefile.test ends here
