### Makefile --- 

## Author: weikent@ubuntu
## Version: $Id: Makefile,v 0.0 2014/07/16 02:15:14 weikent Exp $
## Keywords: 
## X-URL: 


.PHONY : all

all :
	$(MAKE) -f Makefile.epollServer
	$(MAKE) -f Makefile.epollClient
clean:
	$(MAKE) clean -f Makefile.epollServer
	$(MAKE) clean -f Makefile.epollClient




### Makefile ends here